export default {
  ad1: require('./images/ad1.png'),
  avatar: require('./images/avatar.jpg'),
  noData: require('./images/no_log.png'),
  bg: require('./images/bg.jpg'),
  hot0: require('./images/hot_0.png'),
  hot1: require('./images/hot_1.png'),
  hot2: require('./images/hot_2.png'),
  hot3: require('./images/hot_3.png'),
  sale0: require('./images/sale_0.png'),
  sale1: require('./images/sale_1.png'),
  sale2: require('./images/sale_2.png'),
  sale3: require('./images/sale_3.png'),
  nice0: require('./images/nice_0.png'),
  nice1: require('./images/nice_1.png'),
  nice2: require('./images/nice_2.png'),
  nice3: require('./images/nice_3.png'),
  nice4: require('./images/nice_4.png'),
  nice5: require('./images/nice_5.png'),
  nice6: require('./images/nice_6.png'),
  nice7: require('./images/nice_7.png'),
  coupon0: require('./images/coupon_0.png'),
  coupon1: require('./images/coupon_1.png'),
  star1: require('./images/star.png'),
  star2: require('./images/star-1.png')
}
